/**
 * GENERATED by scripts/cdr/register-courses.mjs -- do not edit by hand.
 *
 * One entry per CDR course, derived from that course's master file. The master
 * file is the authority for which reference document each module draws from and
 * for how long each module runs; this is that statement, resolved once so the
 * server does not parse a .docx at call time.
 *
 * Re-run the script after changing a master file or adding a course.
 */

export interface CdrCourseDefinition {
  course_id: string;
  name: string;
  /** Master file name, relative to the course directory. */
  master_file: string;
  /** Course total, as the master file states it. */
  total_hours: number;
  module_count: number;
  /** The reference documents, in the order the master file first mentions them. */
  documents: { doc_key: string; file: string; title: string }[];
  /** Module number to the doc_keys that module may draw from. */
  module_sources: Record<number, string[]>;
  module_titles: Record<number, string>;
}

export const CDR_COURSES: CdrCourseDefinition[] = [
  {
    course_id: 'cdr-biochar',
    name: 'CDR – Biochar',
    master_file: 'master.docx',
    total_hours: 20,
    module_count: 7,
    documents: [
      { doc_key: 'ghg-accounting-and-sustainability-reporting-storyboard', file: 'ghg-accounting-and-sustainability-reporting-storyboard.pdf', title: 'GHG Accounting & Sustainability Reporting_Storyboard' },
      { doc_key: 'circular-carbon-economy-and-vcm-egec-wg-brics-bc', file: 'circular-carbon-economy-and-vcm-egec-wg-brics-bc.pdf', title: 'Circular Carbon Economy & VCM - EGEC WG BRICS BC' },
      { doc_key: 'agri-residues-aggregator', file: 'agri-residues-aggregator.pdf', title: 'Agri Residues Aggregator' },
      { doc_key: 'carbon-removals-through-pyrolysis', file: 'carbon-removals-through-pyrolysis.pdf', title: 'Carbon removals through Pyrolysis' },
      { doc_key: 'dpr-for-biochar-production-1-tph-biomass-feedstock', file: 'dpr-for-biochar-production-1-tph-biomass-feedstock.pdf', title: 'DPR for Biochar Production - 1 TPH Biomass Feedstock' },
      { doc_key: 'dpr-on-biomass-supply-chain-management', file: 'dpr-on-biomass-supply-chain-management.pdf', title: 'DPR on Biomass Supply Chain Management' },
      { doc_key: 'carbon-removal-and-biochar-credits', file: 'carbon-removal-and-biochar-credits.pdf', title: 'Carbon Removal & Biochar Credits' },
      { doc_key: 'dpr-for-biomass-supply-chain-management', file: 'dpr-for-biomass-supply-chain-management.pdf', title: 'DPR for Biomass Supply Chain Management' },
      { doc_key: 'pdd-and-methodology-for-ghg-mitigation', file: 'pdd-and-methodology-for-ghg-mitigation.pdf', title: 'PDD and Methodology for GHG Mitigation' },
    ],
    module_sources: {
      1: ['ghg-accounting-and-sustainability-reporting-storyboard', 'circular-carbon-economy-and-vcm-egec-wg-brics-bc'],
      2: ['agri-residues-aggregator'],
      3: ['carbon-removals-through-pyrolysis'],
      4: ['dpr-for-biochar-production-1-tph-biomass-feedstock'],
      5: ['dpr-on-biomass-supply-chain-management'],
      6: ['carbon-removal-and-biochar-credits'],
      7: ['dpr-for-biomass-supply-chain-management', 'dpr-for-biochar-production-1-tph-biomass-feedstock', 'pdd-and-methodology-for-ghg-mitigation'],
    },
    module_titles: {
      1: 'INTRODUCTION',
      2: 'AGRI RESIDUES supply chain management',
      3: 'Carbon removals through Pyrolysis',
      4: 'Biochar & bio-oil Production',
      5: 'Biochar Sequestration & Digital MRV',
      6: 'Carbon removals & biochar credits',
      7: 'Case Study – Mandya Project',
    },
  },
];
