/**
 * Regenerates src/courses/cdr-generated.ts from every CDR master file on disk.
 *
 * A CDR course is defined by its master file: that document states the modules,
 * their durations, and which reference document each one is built from. Rather
 * than have the server parse a .docx on every call, this script reads the master
 * files once and writes a plain TypeScript module the course registry imports.
 * The generated file is checked in, so what the server will do is reviewable in a
 * diff rather than discovered at runtime.
 *
 * Onboarding a CDR course:
 *   1. mkdir courses/<course-id>
 *   2. put its master file at courses/<course-id>/master.docx
 *   3. node scripts/cdr/register-courses.mjs
 *   4. drop the reference PDFs in under the filenames the script prints
 *
 *   node scripts/cdr/register-courses.mjs [--check]
 *
 * --check exits non-zero if the generated file is out of date, for CI.
 */

import { readdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { parseMasterFile, referencesForModule } from '../../src/cdr/master-file.ts';

const ROOT = path.resolve(import.meta.dirname, '../..');
const COURSES_DIR = path.join(ROOT, 'courses');
const OUT = path.join(ROOT, 'src/courses/cdr-generated.ts');
const MASTER_FILE = 'master.docx';

const quote = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const found = readdirSync(COURSES_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory() && existsSync(path.join(COURSES_DIR, e.name, MASTER_FILE)))
  .map((e) => e.name)
  .sort();

if (found.length === 0) {
  console.error(`No course directory under ${COURSES_DIR} contains a ${MASTER_FILE}.`);
  process.exit(1);
}

const blocks = [];

for (const courseId of found) {
  const masterPath = path.join(COURSES_DIR, courseId, MASTER_FILE);
  const master = await parseMasterFile(masterPath);

  const statedMinutes = Math.round(master.stated_total_hours * 60);
  const computed = master.modules.reduce((a, m) => a + m.minutes, 0);
  if (statedMinutes !== computed) {
    console.error(
      `${courseId}: master file states ${statedMinutes} minutes but its modules sum to ${computed}. ` +
        'Fix the master file; durations are never adjusted here.',
    );
    process.exit(1);
  }
  if (master.stated_module_count !== master.modules.length) {
    console.error(
      `${courseId}: master file says ${master.stated_module_count} modules but ` +
        `${master.modules.length} were parsed.`,
    );
    process.exit(1);
  }

  const documents = master.documents.map((d) => ({ ...d, file: `${d.key}.pdf` }));
  const routing = Object.fromEntries(
    master.modules.map((m) => [m.number, referencesForModule(master, m.number).map((r) => r.key)]),
  );

  console.error(`\n=== ${courseId} : ${master.course_title} ===`);
  console.error(`${master.modules.length} modules, ${master.stated_total_hours} hours`);
  console.error(`\nExpected reference documents in courses/${courseId}/ :`);
  for (const [i, d] of documents.entries()) {
    const present = existsSync(path.join(COURSES_DIR, courseId, d.file));
    console.error(`  ${String(i + 1).padStart(2)}. [${present ? 'present' : 'MISSING'}] ${d.file}`);
    console.error(`        "${d.title}"`);
  }
  for (const m of master.modules) {
    console.error(`  M${m.number} -> ${routing[m.number].join(', ')}`);
  }

  blocks.push(`  {
    course_id: ${quote(courseId)},
    name: ${quote(master.course_title)},
    master_file: ${quote(MASTER_FILE)},
    total_hours: ${master.stated_total_hours},
    module_count: ${master.modules.length},
    documents: [
${documents
  .map(
    (d) => `      { doc_key: ${quote(d.key)}, file: ${quote(d.file)}, title: ${quote(d.title)} },`,
  )
  .join('\n')}
    ],
    module_sources: {
${master.modules
  .map((m) => `      ${m.number}: [${routing[m.number].map(quote).join(', ')}],`)
  .join('\n')}
    },
    module_titles: {
${master.modules.map((m) => `      ${m.number}: ${quote(m.title)},`).join('\n')}
    },
  },`);
}

const body = `/**
 * GENERATED by scripts/cdr/register-courses.mjs -- do not edit by hand.
 *
 * One entry per CDR course, derived from that course's master file. The master
 * file is the authority for which reference document each module draws from and
 * for how long each module runs; this is that statement, resolved once so the
 * server does not parse a .docx at call time.
 *
 * Re-run the script after changing a master file or adding a course.
 */

export interface CdrCourseDefinition {
  course_id: string;
  name: string;
  /** Master file name, relative to the course directory. */
  master_file: string;
  /** Course total, as the master file states it. */
  total_hours: number;
  module_count: number;
  /** The reference documents, in the order the master file first mentions them. */
  documents: { doc_key: string; file: string; title: string }[];
  /** Module number to the doc_keys that module may draw from. */
  module_sources: Record<number, string[]>;
  module_titles: Record<number, string>;
}

export const CDR_COURSES: CdrCourseDefinition[] = [
${blocks.join('\n')}
];
`;

const mode = process.argv[2];
if (mode === '--check') {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== body) {
    console.error('\ncdr-generated.ts is out of date. Run: node scripts/cdr/register-courses.mjs');
    process.exit(1);
  }
  console.error('\ncdr-generated.ts is up to date.');
} else {
  writeFileSync(OUT, body);
  console.error(`\nwrote ${path.relative(ROOT, OUT)}`);
}
